// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: takcontrol.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// TAK Protocol control message
/// This specifies to a recipient what versions
/// of protocol elements this sender supports during
/// decoding.
struct Atakmap_Commoncommo_Protobuf_V1_TakControl {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Lowest TAK protocol version supported
  /// If not filled in (reads as 0), version 1 is assumed
  var minProtoVersion: UInt32 = 0

  /// Highest TAK protocol version supported
  /// If not filled in (reads as 0), version 1 is assumed
  var maxProtoVersion: UInt32 = 0

  /// UID of the sending contact. May be omitted if
  /// this message is paired in a TakMessage with a CotEvent
  /// and the CotEvent contains this information
  var contactUid: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Atakmap_Commoncommo_Protobuf_V1_TakControl: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "atakmap.commoncommo.protobuf.v1"

extension Atakmap_Commoncommo_Protobuf_V1_TakControl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TakControl"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "minProtoVersion"),
    2: .same(proto: "maxProtoVersion"),
    3: .same(proto: "contactUid"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.minProtoVersion) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.maxProtoVersion) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.contactUid) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.minProtoVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.minProtoVersion, fieldNumber: 1)
    }
    if self.maxProtoVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxProtoVersion, fieldNumber: 2)
    }
    if !self.contactUid.isEmpty {
      try visitor.visitSingularStringField(value: self.contactUid, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Atakmap_Commoncommo_Protobuf_V1_TakControl, rhs: Atakmap_Commoncommo_Protobuf_V1_TakControl) -> Bool {
    if lhs.minProtoVersion != rhs.minProtoVersion {return false}
    if lhs.maxProtoVersion != rhs.maxProtoVersion {return false}
    if lhs.contactUid != rhs.contactUid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
