// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: takmessage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Top level message sent for TAK Messaging Protocol Version 1.
struct Atakmap_Commoncommo_Protobuf_V1_TakMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Optional - if omitted, continue using last reported control
  /// information
  var takControl: Atakmap_Commoncommo_Protobuf_V1_TakControl {
    get {return _takControl ?? Atakmap_Commoncommo_Protobuf_V1_TakControl()}
    set {_takControl = newValue}
  }
  /// Returns true if `takControl` has been explicitly set.
  var hasTakControl: Bool {return self._takControl != nil}
  /// Clears the value of `takControl`. Subsequent reads from it will return its default value.
  mutating func clearTakControl() {self._takControl = nil}

  /// Optional - if omitted, no event data in this message
  var cotEvent: Atakmap_Commoncommo_Protobuf_V1_CotEvent {
    get {return _cotEvent ?? Atakmap_Commoncommo_Protobuf_V1_CotEvent()}
    set {_cotEvent = newValue}
  }
  /// Returns true if `cotEvent` has been explicitly set.
  var hasCotEvent: Bool {return self._cotEvent != nil}
  /// Clears the value of `cotEvent`. Subsequent reads from it will return its default value.
  mutating func clearCotEvent() {self._cotEvent = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _takControl: Atakmap_Commoncommo_Protobuf_V1_TakControl? = nil
  fileprivate var _cotEvent: Atakmap_Commoncommo_Protobuf_V1_CotEvent? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Atakmap_Commoncommo_Protobuf_V1_TakMessage: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "atakmap.commoncommo.protobuf.v1"

extension Atakmap_Commoncommo_Protobuf_V1_TakMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TakMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "takControl"),
    2: .same(proto: "cotEvent"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._takControl) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._cotEvent) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._takControl {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._cotEvent {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Atakmap_Commoncommo_Protobuf_V1_TakMessage, rhs: Atakmap_Commoncommo_Protobuf_V1_TakMessage) -> Bool {
    if lhs._takControl != rhs._takControl {return false}
    if lhs._cotEvent != rhs._cotEvent {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
